### ISSUE TITLE
fm24 ri_1_LOC file errors

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#11]
fmpolicytc: 6 layers per agg_id are being created at level 1 and there should only be 1 layer. 
fmpolicytc: calcrule 3-8 are not being assigned to agg_ids 1-10
fmprofile: ok
fmprogramme: to_agg_ids 1-4 and 5-8 are jumbled up with respect to from_agg_ids 1-27 at level 1.

**Comment by johcarter** [comment]
fmprogramme agg_id order is as a result of sorting location number ascending and they are alphanumeric. so thats ok

**Comment by sambles** [comment]
https://github.com/OasisLMF/ReinsuranceTestTool/blob/dev/reinsurance_layer.py#L554-L584: 

Duplicate layers: `layer_id = layer_id + 1` for each row without checking `ReinsLayerNumber` value from *ri_info.csv*

**Comment by sambles** [comment]
Update:
ri_1_LOC - ok
ri_2_LOC - wrong
ri_3_LOC - wrong

**Comment by sambles** [comment]
`ri_1_LOC` / `ri_2_LOC` look correct as of ff814881e5a8ddef3dc3b3db1c2f3b8305e800d7

**Comment by johcarter** [comment]
Agreed. See comparison2
