### ISSUE TITLE
notebook Step 1 error on first run (Stable and Dev)

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#18]
The first time you run Step 1 in the notebook this error happens. Second time it doesnt
/srv/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/srv/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

Low priority

**Comment by sambles** [comment]
This warning comes from the python numpy package. Reverting to `1.14.5` from `1.15.0`
