### ISSUE TITLE
Display PortfolioNumber in reinsurance scope file in notebook 

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#19]
It would be good if PortfolioNumber appears in the reinsurance scope notebook so that the link to the account data is clear and also so that when the RIscope risk level is SEL it is clear which portfolios this applies to (I know there is only 1!)

**Comment by aiste-kalinauskaite** [comment]
Anywhere, where RiskLevel = SEL, you should have what that selection applies to, and usually that's a portfolio number.
