### ISSUE TITLE
Multiple_SS example - changing occurrence limits does not change net losses

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/ReinsuranceTestTool#24]
Even when occurrence limit is changed to 1, and with no changes in example, this should have an impact on losses, net loss numbers are identical to the initial example.

**Comment by johcarter** [comment]
It works for me, Aiste. please see potential fix suggestion in  #26

**Comment by aiste-kalinauskaite** [comment]
It looks ok now, if % placed = 1 in both treaties.

**Comment by johcarter** [comment]
Fixed in v0.4 (dev). @aiste-kalinauskaite  please can you retest and close issue if you agree? thanks

**Comment by aiste-kalinauskaite** [comment]
I ran a couple of tests, it's working as expected now.
