### ISSUE TITLE
No policy share field in #3 account info

### ISSUE THREAD

**Issue by carlholden** [OasisLMF/ReinsuranceTestTool#25]
Hi Joh - please can you put a policy share field in the reinsurance test tool? In #3 it should be there. 

Thanks

Carl

**Comment by johcarter** [comment]
Please see request to implement Participation field in account file. 
@carlholden we intend to implement all the direct terms after reinsurance is working.

**Comment by johcarter** [comment]
@carlholden we have implemented PolicyParticipation but its not editable through the front end. the workaround is to edit the file and use the file uploader in notebook. let me know if you would like me to demonstrate
