### ISSUE TITLE
Simple_CAT_XL contains LocationNumber

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/ReinsuranceTestTool#27]
CAT XLs will always apply to selection (SEL), so it's just misleading to provide an example that has LocationNumber = 1. Especially, that regardless of whether it is in or out, the results are the same.

**Comment by johcarter** [comment]
I will update example

**Comment by aiste-kalinauskaite** [comment]
Thank you very much!

**Comment by johcarter** [comment]
Updated and test passes (dev branch). You're welcome.
