### ISSUE TITLE
Multiple_CAT_XL % ceded on same layer treaties exceed 100%

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/ReinsuranceTestTool#28]
Any type of reinsurance, if it applies to identical layer, % ceded over all of those layers cannot exceed 100%. Example shows that there are two 10 xs 50 layers and each cedes 100%. We will, of course, have such validation for OED, but example is somewhat misleading.

**Comment by johcarter** [comment]
I will update example to 50% each

**Comment by aiste-kalinauskaite** [comment]
Thanks, Joh! Following the discussion and the industry poll we did, I think this particular example (i.e. CAT XLs) would be using % placed fields, rather than % ceded. But they too, can't exceed more than 100% when summed over the same layer.

**Comment by johcarter** [comment]
I think PercentPlaced is implemented in the dev branch so i will use this field instead to test it.
