### ISSUE TITLE
QS can't have RiskLevel = SEL

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/ReinsuranceTestTool#29]
Because sometimes there will be QS with risk limits, we won't allow having RiskLevel = SEL for QS reinsurance type. So even if there isn't RiskLimit, we still expect, e.g. ACC RiskLevel. Calculations don't change, it's just in the example, perhaps better not to introduce the "wrong" way of presenting information.

**Comment by johcarter** [comment]
The numbers don't change whether you use ACC, LOC or POL. I will update the example to use ACC RiskLevel

**Comment by aiste-kalinauskaite** [comment]
Thanks, Joh! Yes, the numbers for QS shouldn't change if you only have share and occurrence limit. They would change though, if there was per risk limit. But it's a separate thing (and, of course, there is an exception that if each account had just one policy and each policy had just one account, then QS numbers would always be the same).

Once you update an example, the issue can be closed.

**Comment by johcarter** [comment]
Updated and tests pass
