### ISSUE TITLE
Changing TreatyPercent changes net loss

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/ReinsuranceTestTool#30]
Changing TreatyPercent shouldn't change the value of net loss. The only reason for TreatyPercent is to allow reinsurers to calculate their share of the risk - it shouldn't impact an insurers net loss at all, yet it does (e.g. changing this in the example loc_limit_QS).

Also, TreatyPercent should be renamed TreatyShare, per OED, to distinguish it from the other RI percent fields that do impact net loss.

Suggest removing TreatyPercent from v1 of the RI to avoid confusion.

**Comment by sambles** [comment]
Can you help me reproduce this issue.  What values of  `TreatyShare` did you use?

**Comment by johcarter** [comment]
I couldn't replicate this. Also as well as making the change in the grid in the UI, i made a copy of the files and changed treaty percent to 0.5 and it still didn't change the numbers. We're pretty sure this field is not being used in the creation of fm files..

**Comment by aiste-kalinauskaite** [comment]
This is going to be really weird, as I cannot reproduce it either. However, I saw it on Matt's computer at the time he raised this issue (i.e. net numbers have changed and he was able to save a percentage other than 1 or 0), When I am trying this today on simple_QS file - I cannot even save it to anything else than 0 or 1, i.e. when typing e.g. 0.5 or 0.1, it switches to 0. I will check out loc_limit_QS file now.

**Comment by aiste-kalinauskaite** [comment]
I can't save it anything else than 0 or 1 in loc_limit_QS field. Has the code been updated between Wednesday evening and today?..

**Comment by johcarter** [comment]
No it hasn't changed, Aiste. Lets keep this open for a few days and see if it reoccurs
