### ISSUE TITLE
100k location test failed

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#4]
In Step 8 got this error
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-9-6d84498ad0e6> in <module>()
      1 # Step 8 - run the OED data though the Oasis Financial Module and output the losses by item at each inuring level.
----> 2 net_losses = reinsurance_tester.run_test('test', account_df, location_df, ri_info_df, ri_scope_df, loss_factor=1.0, do_reinsurance=do_reinsurance)
      3 print("Ran {} inuring layers".format(len(net_losses) - 1))
      4 print("Losses for:")
      5 for key in net_losses.keys():

~/reinsurance_tester.py in run_test(run_name, account_df, location_df, ri_info_df, ri_scope_df, loss_factor, do_reinsurance)
    149         direct_layer.write_oasis_files()
    150         losses_df = direct_layer.apply_fm(
--> 151             loss_percentage_of_tiv=loss_factor, net=False)
    152         net_losses['Direct'] = losses_df
    153         if do_reinsurance:

~/direct_layer.py in apply_fm(self, loss_percentage_of_tiv, net)
    200         proc.wait()
    201         if proc.returncode != 0:
--> 202             raise Exception("Failed to run fm")
    203         losses_df = pd.read_csv("ils.csv")
    204         losses_df.drop(losses_df[losses_df.sidx != 1].index, inplace=True)

Exception: Failed to run fm

Test data is in examples/volume_simple_QS
note that location file needs to be untarred

**Comment by sambles** [comment]
fm_policytc.csv <-- duplicate entries

**Comment by sambles** [comment]
At 100k locations, system with 64GB runs out of memory.  50k Runs at about 30GB and completes

**Comment by johcarter** [comment]
Ran on hosted env (binder)
Exec time: 269.87207889556885
