### ISSUE TITLE
Mixed scope filtering for QS and CAT XL

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#46]
We can't apply different calcrules to different risk level groupings within a treaty. But we could do a straight filter across mixed scope fields if there are no risk level terms (QS, CAT XL)

I wonder if we could implement mixed risk level filtering for these types as follows;

1. Write a routine to work out from the filters what the subset of locations are that are covered by the treaty. 
2. Set  RiskLevel to LOC (the scope file might have different values, but ignore it)
3. fm Level1 : Group to location level and apply passthrough calcrule 12 to the locations in scope and calcrule 14 to the rest
4. fm Level2: Group to treaty level and apply quota or cat xl calcrule.

To prioritise

**Comment by johcarter** [comment]
I have checked the example OED in the spec and the RiskLevel would be mixed. The rule would therefore be, if there is more than one RiskLevel for a contract, set RiskLevel to LOC.

**Comment by sambles** [comment]
add flag for mixed riskLevel filtering:
https://github.com/OasisLMF/OasisLMF/blob/feature/reinsurance/oasislmf/exposures/reinsurance_layer.py#L275-L290

**Comment by sambles** [comment]
Notes on Scope filter from @Aaiste-kalinauskaite

I can see below combinations being used in practice:
 
PortNumber, AccNumber & LocNumber <- note, you don’t need to have PolNumber, if you are using LocNumber and it applies for the entire account, and not just for one layer (for example)
PortNumber & AccNumber
Portnumber, AccNumber & PolNumber
Portnumber, AccNumber, PolNumber & LocNumber
 
So the above are for filtering scope. The example below explains how this works with RiskLevel and that filtering scope option is not tied to RiskLevel.
 
You can specify PortNumber & AccNumber, but RiskLevel = LOC. For example, you have 5 accounts, but between them they have 1 million locations, so filtering by account is rather efficient, as you only have to enter 5 records in Reins_scope field. However, you may still want to apply risk terms (RiskLimit & RiskAttachment) per location (i.e. RiskLevel = LOC) within the scope specified.
 
In terms of filtering entire portfolio on AccNumber field, it is possible, but the users would not be happy (think of cases where portfolio consists of thousands of accounts, as this would mean providing thousands of records in reins_scope file).

**Comment by mpinkerton-oasis** [comment]
Fixed in 397
