### ISSUE TITLE
3 CAT XL layers with strange net losses

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/ReinsuranceTestTool#48]
I ran 3 CAT XL layers, and was expecting net loss to be 325 (ceding 75 to reinsurer), but got 350.

Layers run:
I ran 3 stacked layers (inuring priority = 1,1,1; ReinsLayerNumber = 1,2,3):

50 xs 50
50 xs 100
50 xs 150
all with % placed = 0.5

P.S. Same result if I use ReinsLayerNumber = 1,1,1

**Comment by sambles** [comment]
same as issue #39
