### ISSUE TITLE
acc_1_CAT_XL Not filtering using SEL + AccountNum field

### ISSUE THREAD

**Issue by sambles** [OasisLMF/ReinsuranceTestTool#54]

**Comment by sambles** [comment]
Logic in CAT_XL needs fixing:
https://github.com/OasisLMF/OasisLMF/blob/feature/reinsurance/oasislmf/exposures/reinsurance_layer.py#L523-L571

- should always be of type `SEL`? 
- need to noloss / passthroguh rules depending on filtered nodes

**Comment by mpinkerton-oasis** [comment]
Old issue - closing
