### ISSUE TITLE
Scope filters not taking into account correct field sets

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/ReinsuranceTestTool#55]
Currently we have:
Location scope -> LocNum
Policy scope -> PolicyNum
Account scope -> AccountNum
Portfolio scope -> Not implemented

This should be:
Location scope -> LocNum, PolicyNum, AccountNum
Policy scope -> PolicyNum, AccountNum
Account scope -> AccountNum

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisLMF/commit/cf4e1d2b947e8771f12e1597bf3b6e93a5180084
