### ISSUE TITLE
error PortNumber is not an integer

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#60]
In dev branch using example LOC_PR_filter_P2;
Example tries to filter a Location Per Risk Treaty on PortNumber = P2

Error:
[{'check': 'datatypes', 'scope': 'ri_info file', 'messsages': ["Type error in column 'PortNumber': expected '[dtype('int64'), dtype('float64')]'  found 'object'"], 'meta_data': ''}]
Exec time: 0.2039628028869629

despite the misleading field name, PortNumber is a varchar field not an int.

**Comment by johcarter** [comment]
Also, filtering on PortNumber alone (when it is an integer) runs but does not seem to take effect. Both portfolios in this example have losses.

**Comment by mpinkerton-oasis** [comment]
PortNumber is not implemeneted yet as a scope or filter. 

(also, can we log different points as separate issues so we track independently)

**Comment by johcarter** [comment]
ok will create a new issue for this

**Comment by mpinkerton-oasis** [comment]
Fixed
