### ISSUE TITLE
Filtering on PortNumber and AccNumber doesnt work for PR LOC

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#62]
Dev branch
Examples 
loc_PR_filter_P2_A3
simple_CAT_XL_filter_P2_A3

Example tries to filter on (PortNumber and ) AccNumber = A3. All accounts take losses.

**Comment by mpinkerton-oasis** [comment]
Fixed. Test cases:
simple_CXL_port_acc_filter
single_loc_level_PR_acc_filter
