### ISSUE TITLE
Filtering on PortNumber and AccNumber and PolNumber doesnt work for PR LOC

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#63]
Dev branch
Example loc_PR_filter_P1_A1_L2

Example tries to filter on (PortNumber and ) AccNumber = A1 , and PolNumber=L2. All accounts and policies take losses.

**Comment by mpinkerton-oasis** [comment]
Fixed. Test case:
single_loc_level_PR_pol_filter
