### ISSUE TITLE
Filtering on PortNumber, AccNumber, PolNumber and LocNumber doesnt work for PR LOC

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#64]
Dev branch
Example loc_PR_filter_P1_A1_L2_LOC1

Example tries to filter on (PortNumber and ) AccNumber = A1 , and PolNumber=L2 and LocNumber = LOC1. All policies take losses.

**Comment by mpinkerton-oasis** [comment]
Fixed. Test case:
single_loc_level_PR_pol_and_loc_filter
