### ISSUE TITLE
Filtering on PortNumber and AccNumber and LocNumber doesnt work for Cat XL

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#65]
Dev branch
Example simple_CAT_XL_filter_P1_A1_LOC1

Example tries to filter on (PortNumber and ) AccNumber = A1 and LocNumber = 1. All locations take losses.

**Comment by mpinkerton-oasis** [comment]
Fixed. Test case:
simple_CXL_port_acc_pol_loc_filter

**Comment by mpinkerton-oasis** [comment]
Fixed. Test case:
simple_CXL_port_acc_pol_loc_filter
