### ISSUE TITLE
Increase notebook timeout to 1 hour

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#71]
I realise this is a cost issue but could we have version of notebook with a longer timeout? 10 mins is not enough. we are talking about occasional use from 3 testers (myself, matt and Aiste)

**Comment by johcarter** [comment]
Jupyter notebook can't be run locally in bash under Windows because bash under windows lacks the graphical interface. And if jupyter is installed in Windows, the test tool invokes the MDK which doesn't run in windows.

What are the other options for running the test tool locally on a windows machine (using linux subsystem)?

**Comment by mpinkerton-oasis** [comment]
Docker might be a good option.

**Comment by johcarter** [comment]
local installation solution found
