### ISSUE TITLE
fm24 fails to run

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ReinsuranceTestTool#8]
Step 8 error:

Exec time: 0.20032334327697754
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-13-5a06428ebdc3> in <module>()
      1 # Step 8 - run the OED data though the Oasis Financial Module and output the losses by item at each inuring level.
----> 2 net_losses = reinsurance_tester.run_test('run_reinsurance', account_df, location_df, ri_info_df, ri_scope_df, loss_factor=1.0, do_reinsurance=do_reinsurance)
      3 print("Ran {} inuring layers".format(len(net_losses) - 1))
      4 print("Losses for:")
      5 for key in net_losses.keys():

~/reinsurance_tester.py in run_test(run_name, account_df, location_df, ri_info_df, ri_scope_df, loss_factor, do_reinsurance)
    153         direct_layer.write_oasis_files()
    154         losses_df = direct_layer.apply_fm(
--> 155             loss_percentage_of_tiv=loss_factor, net=False)
    156         net_losses['Direct'] = losses_df
    157         if do_reinsurance:

~/direct_layer.py in apply_fm(self, loss_percentage_of_tiv, net)
    200         proc.wait()
    201         if proc.returncode != 0:
--> 202             raise Exception("Failed to run fm")
    203         losses_df = pd.read_csv("ils.csv")
    204         losses_df.drop(losses_df[losses_df.sidx != 1].index, inplace=True)

Exception: Failed to run fm

**Comment by sambles** [comment]
Exception fixed, but number need adjusting #11
